In [12]:
# Assignment 1 Woking with numpy
import numpy as np

In [14]:
# Creating a 1D array with integers from 1 to 20
array_1d = np.arange(1, 21)

# a. Performing calculations
sum_value = np.sum(array_1d)
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
std_dev = np.std(array_1d)

# b. Finding indices of elements greater than 10
indices = np.where(array_1d > 10)

print(sum_value, mean_value, median_value, std_dev, indices)


210 10.5 10.5 5.766281297335398 (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)


In [16]:
# Creating a 4x4 array
array_2d = np.arange(1, 17).reshape(4, 4)

# a. Printing array
print(array_2d)

# b. Finding the transpose
transpose = array_2d.T

# c. Row-wise and column-wise sums
row_sums = np.sum(array_2d, axis=1)
col_sums = np.sum(array_2d, axis=0)

print(transpose, row_sums, col_sums)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]] [10 26 42 58] [28 32 36 40]


In [18]:
# Creating two random 3x3 arrays
array_a = np.random.randint(1, 21, size=(3, 3))
array_b = np.random.randint(1, 21, size=(3, 3))

# a. Element-wise operations
addition = np.add(array_a, array_b)
subtraction = np.subtract(array_a, array_b)
multiplication = np.multiply(array_a, array_b)

# b. Dot product
dot_product = np.dot(array_a, array_b)

print(addition, subtraction, multiplication, dot_product)


[[20 38  9]
 [29 26 12]
 [35 32 20]] [[-12   0   3]
 [  9  10   4]
 [ -1  -4 -16]] [[ 64 361  18]
 [190 144  32]
 [306 252  36]] [[362 336 196]
 [628 649 273]
 [448 471 143]]


In [20]:
# Creating a 1D array and reshape it
array_to_reshape = np.arange(1, 13).reshape(3, 4)

# Slicing the first two rows and last two columns
sliced_array = array_to_reshape[:2, -2:]

print(array_to_reshape, sliced_array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] [[3 4]
 [7 8]]
